Improve documentation, better name volumes.

diff --git a/ac-mount-all b/ac-mount-all
--- a/ac-mount-all
+++ b/ac-mount-all
@@ -3,19 +3,48 @@
 : <<=cut
 =pod
 
-=head1
+=head1 NAME
+
+ac-mount-all - Mounts and manages encrypted volumes by using keyfiles.
+
+=head1 SYNOPSIS
+
+ac-mount-all {start|stop|mount-keys|umount-keys|create-volume}
+
+=head1 DESCRIPTION
 
 Mounts a list of encrypted LVM volumes by using a disk stored keyfile and a
 passphrase. Configuration is simple.
 
-To create the keys volume:
-  lvcreate -L 100M -n encrypted-keys system 
-  cryptsetup luksFormat /dev/system/encrypted-keys --cipher=aes-cbc-essiv:sha256 --key-size=256 --verify-passphrase 
-  cryptsetup luksOpen /dev/system/encrypted-keys dmcrypt-keys
-  mkfs.ext3 /dev/mapper/dmcrypt-keys
+=head1 SETUP
+
+=over 2
+
+=item Install all the needed tools:
+
+  apt-get install cryptsetup
+
+=item Create a volume where to store all your keys:
+
+  lvcreate -L 20M -n encrypted-keys system 
+
+=item Encrypt the key volume:
+
+  cryptsetup luksFormat /dev/system/encrypted-keys \
+      --cipher=aes-cbc-essiv:sha256 --key-size=256 --verify-passphrase 
+
+=item Format the new volume:
+ 
+  cryptsetup luksOpen /dev/system/encrypted-keys cleartext-keys
+  mkfs.ext4 /dev/mapper/cleartext-keys
+
+=back
 
 To create a new volume:
   $0 create-volume group name
+
+
+=head1 COPYRIGHT
 
 Copyright (C) 2006-2013 Carlo Contavalli, Andrea Ciancone, Fernando Vezzosi
   
@@ -69,8 +98,8 @@ lvcreate -L <size> -n encrypted-$volume_name $volume_group
 cryptsetup luksFormat /dev/$volume_group/encrypted-$volume_name \\
     --cipher=aes-cbc-essiv:sha256 --key-size=256 --key-file=$cfg_key_mount/$volume_group-$volume_name.key
 cryptsetup luksOpen --key-file=$cfg_key_mount/$volume_group-$volume_name.key \\
-     /dev/$volume_group/encrypted-$volume_name dmcrypt-$volume_name
-mkfs.ext3 /dev/mapper/dmcrypt-$volume_name
+     /dev/$volume_group/encrypted-$volume_name cleartext-$volume_name
+mkfs.ext3 /dev/mapper/cleartext-$volume_name
 
 REMEMBER TO LOCK THE KEYS AFTERWARD!
 EOF
@@ -78,26 +107,26 @@ EOF
 
 function protect_keys() {
   # Make sure keys are not mounted... when we exit :)
-  trap 'umount "$cfg_key_mount" &>/dev/null && cryptsetup luksClose dmcrypt-keys &>/dev/null' EXIT
+  trap 'umount "$cfg_key_mount" &>/dev/null && cryptsetup luksClose cleartext-keys &>/dev/null' EXIT
 }
 
 function umount_keys() {
   echo " + umounting keys"
   umount "$cfg_key_mount" || true
   echo " + removing keys"
-  cryptsetup luksClose dmcrypt-keys
+  cryptsetup luksClose cleartext-keys
 }
 
 function mount_keys() {
   mountoptions=${1-ro}
   echo " + trying to mount keys."
   for attempt in `seq 1 $cfg_attempts`; do 
-    cryptsetup luksOpen "/dev/$cfg_key_volume" dmcrypt-keys
-    fsck -n /dev/mapper/dmcrypt-keys &>/dev/null || { 
+    cryptsetup luksOpen "/dev/$cfg_key_volume" cleartext-keys
+    fsck -n /dev/mapper/cleartext-keys &>/dev/null || { 
       status="$?"; 
       test "$status" == "8" || break; 
       echo "wrong password? please try again..."
-      cryptsetup luksClose dmcrypt-keys
+      cryptsetup luksClose cleartext-keys
       continue
     }
   
@@ -106,14 +135,14 @@ function mount_keys() {
   done
   
   test "$status" == 0 || {
-    echo "fsck -n /dev/mapper/dmcrypt-keys - failed ($status)! Please check partition manually" 1>&2
-    echo "make sure to run cryptsetup luksClose dmcrypt-keys when you are done!" 1>&2
+    echo "fsck -n /dev/mapper/cleartext-keys - failed ($status)! Please check partition manually" 1>&2
+    echo "make sure to run cryptsetup luksClose cleartext-keys when you are done!" 1>&2
     exit 1
   }
   
   echo " + mounting keyfile"
-  mount -o $mountoptions /dev/mapper/dmcrypt-keys "$cfg_key_mount" || {
-    echo "mount failed! Please check /dev/mapper/dmcrypt-keys manually!" 1>&2
+  mount -o $mountoptions /dev/mapper/cleartext-keys "$cfg_key_mount" || {
+    echo "mount failed! Please check /dev/mapper/cleartext-keys manually!" 1>&2
     exit 2
   }
 }
@@ -126,7 +155,7 @@ function umount_volumes() {
 
     options=${options-none}
   
-    echo " + umounting /dev/mapper/dmcrypt-$enc - $fs - $mount"
+    echo " + umounting /dev/mapper/cleartext-$enc - $fs - $mount"
     umount "$mount" || {
       echo "umount failed. Device in use? skipped."
       continue
@@ -138,9 +167,9 @@ function umount_volumes() {
       ""|\#*) continue;;
     esac
 
-    echo "   + removing device mapper/dmcrypt-$enc"
-    cryptsetup luksClose /dev/mapper/"dmcrypt-$enc" || {
-      echo "cryptsetup luksClose /dev/mapper/dmcrypt-$enc -- failed!"
+    echo "   + removing device mapper/cleartext-$enc"
+    cryptsetup luksClose /dev/mapper/"cleartext-$enc" || {
+      echo "cryptsetup luksClose /dev/mapper/cleartext-$enc -- failed!"
       continue
     }
   done < "$cfg_fstab"
@@ -158,14 +187,14 @@ function mount_volumes() {
       continue
     }
   
-    test ! -b "/dev/mapper/dmcrypt-$enc" || {
-      echo "  + device already decrypted, skipping mapper/dmcrypt-$enc"
+    test ! -b "/dev/mapper/cleartext-$enc" || {
+      echo "  + device already decrypted, skipping mapper/cleartext-$enc"
       continue
     }
   
-    echo "   + creating device mapper/dmcrypt-$enc"
-    cryptsetup --key-file="$cfg_key_mount/$volume-$enc.key" luksOpen "/dev/$volume/encrypted-$enc" "dmcrypt-$enc" || {
-      echo "cryptsetup --key-file=$cfg_key_mount/$volume-$enc.key luksOpen /dev/$volume/encrypted-$enc dmcrypt-$enc -- failed!"
+    echo "   + creating device mapper/cleartext-$enc"
+    cryptsetup --key-file="$cfg_key_mount/$volume-$enc.key" luksOpen "/dev/$volume/encrypted-$enc" "cleartext-$enc" || {
+      echo "cryptsetup --key-file=$cfg_key_mount/$volume-$enc.key luksOpen /dev/$volume/encrypted-$enc cleartext-$enc -- failed!"
       continue
     }
   done < "$cfg_fstab"
@@ -180,13 +209,13 @@ function mount_volumes() {
 
     options=${options-none}
   
-    if mount |grep /dev/mapper/dmcrypt-$enc &>/dev/null; then
-      echo "  + /dev/mapper/dmcrypt-$enc already mounted, skipping"
+    if mount |grep /dev/mapper/cleartext-$enc &>/dev/null; then
+      echo "  + /dev/mapper/cleartext-$enc already mounted, skipping"
       continue
     fi
   
-    test -b "/dev/mapper/dmcrypt-$enc" || {
-      echo "something bad happened - device /dev/mapper/dmcrypt-$enc does not exist"
+    test -b "/dev/mapper/cleartext-$enc" || {
+      echo "something bad happened - device /dev/mapper/cleartext-$enc does not exist"
       exit 6
     }
   
@@ -195,15 +224,15 @@ function mount_volumes() {
       continue
     }
   
-    echo " + fsck /dev/mapper/dmcrypt-$enc"
-    fsck -p /dev/mapper/"dmcrypt-$enc" || { 
-      echo "fsck on /dev/mapper/dmcrypt-$enc failed - please correct errors manually"
+    echo " + fsck /dev/mapper/cleartext-$enc"
+    fsck -p /dev/mapper/"cleartext-$enc" || { 
+      echo "fsck on /dev/mapper/cleartext-$enc failed - please correct errors manually"
       continue
     }
   
-    echo " + mounting /dev/mapper/dmcrypt-$enc - $fs - $mount"
-    mount -o "$options" -t "$fs" /dev/mapper/"dmcrypt-$enc" "$mount" || {
-      echo "mount of /dev/mapper/dmcrypt-$enc in $mount ($options - $fs) failed - please correct errors manually"
+    echo " + mounting /dev/mapper/cleartext-$enc - $fs - $mount"
+    mount -o "$options" -t "$fs" /dev/mapper/"cleartext-$enc" "$mount" || {
+      echo "mount of /dev/mapper/cleartext-$enc in $mount ($options - $fs) failed - please correct errors manually"
       continue
     }
   done < "$cfg_fstab"
